
services:
  backend:
    build: ./backend
    container_name: backend_bachhoa
    restart: always
    ports:
      - "5001:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - ZALO_PAY_KEY1=${ZALO_PAY_KEY1}
      - ZALO_PAY_KEY2=${ZALO_PAY_KEY2}
    depends_on:
      - mongodb

  chatbot:
    build: ./chatbotRAG
    container_name: chatbot_rag
    restart: always
    ports:
      - "8001:8001"
    env_file:
      - ./chatbotRAG/.env

  mongodb:
    image: mongo:6
    container_name: mongo_bachhoa
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:

