# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deploy Bach-hoa App

on:
  push:
    branches: [ "main" ]

jobs:
  deploy: 
    runs-on: ubuntu-latest

    steps:
    - name: Deploy using SSH
      uses: appleboy/ssh-action@master
      with:
        node-version: ${{ matrix.node-version }}
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: 22
        scripts: | 
          cd $HOME/bach-hoa-project/backend
          git fetch origin
          git pull
          npm install
          pm2 reload backend-bachoa || pm2 start server.js --name backend-bachhoa
          pm2 save
          pm2 list
